apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiiteapp
spec:
  selector:
    matchLabels:
      app: aiiteapp
  template:
    metadata:
      labels:
        app: aiiteapp
    spec:
      containers:
      - name: aiiteapp
        image: amrish24/aiite-app-img:1
        resources:
        ports:
        - containerPort: 8080
          name: aiiteapp-port
