apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiiteapp
spec:
  selector:
    matchLabels:
      app: aiiteapp
  template:
    metadata:
      labels:
        app: aiiteapp
    spec:
      containers:
      - name: aiiteapp
        image: amrish24/aiite-app-img:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: aiiteapp-port